// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"

	"github.com/google/uuid"
)

type Comment struct {
	CommentID   uuid.UUID `json:"commentID"`
	PostID      uuid.UUID `json:"postID"`
	UserID      uuid.UUID `json:"userID"`
	Content     string    `json:"content"`
	DateCreated time.Time `json:"dateCreated"`
}

type Post struct {
	PostID      uuid.UUID `json:"postID"`
	UserID      uuid.UUID `json:"userID"`
	Title       string    `json:"title"`
	Body        string    `json:"body"`
	DateCreated time.Time `json:"dateCreated"`
}

type RevokedToken struct {
	Token       string    `json:"token"`
	DateCreated time.Time `json:"dateCreated"`
}

type Subscribtion struct {
	SubscriberID uuid.UUID `json:"subscriberID"`
	BloggerID    uuid.UUID `json:"bloggerID"`
}

type User struct {
	UserID      uuid.UUID `json:"userID"`
	Username    string    `json:"username"`
	Password    string    `json:"password"`
	DateCreated time.Time `json:"dateCreated"`
}
